
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make install-libs"

run-hello-world:
	ruby hello-world/hello-world.rb

run-fibonacci:
	ruby fibonacci/fibonacci.rb

install-libs:
	apt-get install ruby
