
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make install-libs"

run-hello-world:
	gst hello-world/hello-world.st

run-fibonacci:
	gst fibonacci/fibonacci.st

install-libs:
	apt-get install gnu-smalltalk
