
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make run-nodejs"
	@echo "make install-libs"

run-hello-world:
	rhino hello-world/hello-world.js

run-fibonacci:
	rhino fibonacci/fibonacci.js

run-nodejs:
	node nodejs/nodejs.js

install-libs:
	apt-get install rhino nodejs
