
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make install-libs"

run-hello-world:
	python hello-world/hello-world.py

run-fibonacci:
	python fibonacci/fibonacci.py

install-libs:
	apt-get install python
