
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make clean"
	@echo "make install-libs"

run-hello-world:
	cd hello-world; scala HelloWorld.scala

run-fibonacci:
	cd fibonacci; scala Fibonacci.scala

install-libs:
	apt-get install scala

