
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make install-libs"

run-hello-world:
	php hello-world/hello-world.php

run-fibonacci:
	php fibonacci/fibonacci.php

run-nette:
	echo "You must copy folder nette into /var/www and open it with your browser.\nApache2 & PHP5 & sqlite2 needed.\n"
	php nette/www/index.php

install-libs:
	apt-get install php

