
all:
	@echo "make run-hello-world"
	@echo "make run-fibonacci"
	@echo "make install-libs"

run-hello-world:
	php hello-world/hello-world.php

run-fibonacci:
	php fibonacci/fibonacci.php

install-libs:
	apt-get install php

